(SIMP-1695) Use simp_options module for global catalysts
simp/pupmod-simp-snmpd pull request #14
Opened 2016-12-07 17:41 UTC by lnemsick-simp

SIMP-2196 #close
SIMP-1695 #comment

2016-12-07 18:00 UTC, jeefberkey approved these changes

2016-12-07 18:00 UTC, nick-markowski requested changes
This module needs to require the simp_opt module (metadata, build/requires).  I believe it also needs a major bump.

EDIT: Apparently not. Ticket updated.

2016-12-07 18:05 UTC, nick-markowski approved these changes

2016-12-07 20:26 UTC, lamawithonel commented on manifests/utils.pp
> +  $rsync_timeout = lookup('::simp_options::rsync::timeout', { 'default_value' => '2', 'value_type' => String }),
These should be static. The `lookup()` function does not look at the variable namespace, so if a user modifies `::simp_options` via profile and sets a different value in Hiera the values will diverge. The logic should go in the module's `<module_name>::data` function.

See: https://docs.puppet.com/puppet/latest/lookup_quick_module.html#more-about-the-function-data-provider

2016-12-07 20:57 UTC, lnemsick-simp commented
lookup should be lookup('simp_options::rsync::server',  { 'default_value' => '127.0.0.1', 'value_type' => String}),

Don't merge

2016-12-08 14:45 UTC, lnemsick-simp commented
Work incomplete. Don't approve!!!

2016-12-08 16:42 UTC, lnemsick-simp commented
Ready for re-review

2016-12-08 18:28 UTC, nick-markowski requested changes
This looks great, but we should include simp_options in fixtures for best testing

2016-12-08 22:11 UTC, nick-markowski approved these changes

2016-12-08 22:12 UTC, merged